export const CITIES = {
  chicago: {
    id: 'chicago',
    name: 'Chicago',
    state: 'IL',
    center: [41.8781, -87.6298],
    zoom: 11,
    type: 'soda',
    endpoint: 'https://data.cityofchicago.org/resource/ijzp-q8t2.json',
    dateField: 'date',
    nullCheck: 'latitude',
    fields: {
      id: 'id',
      type: 'primary_type',
      description: 'description',
      date: 'date',
      lat: 'latitude',
      lng: 'longitude',
      address: 'block',
      neighborhood: 'community_area',
      district: 'district',
      caseNumber: 'case_number',
    },
    neighborhoodTransform: 'chicago_community_area',
  },

  detroit: {
    id: 'detroit',
    name: 'Detroit',
    state: 'MI',
    center: [42.3314, -83.0458],
    zoom: 12,
    type: 'arcgis',
    endpoint: 'https://services2.arcgis.com/qvkbeam7Wirps6zC/arcgis/rest/services/RMS_Crime_Incidents/FeatureServer/0/query',
    dateField: 'incident_occurred_at',
    dateType: 'epoch',
    fields: {
      id: 'crime_id',
      type: 'offense_category',
      description: 'offense_description',
      date: 'incident_occurred_at',
      lat: 'latitude',
      lng: 'longitude',
      address: 'nearest_intersection',
      neighborhood: 'neighborhood',
      district: 'police_precinct',
      caseNumber: 'case_id',
    },
  },

  nyc: {
    id: 'nyc',
    name: 'New York',
    state: 'NY',
    center: [40.7128, -74.006],
    zoom: 11,
    type: 'soda',
    endpoint: 'https://data.cityofnewyork.us/resource/5uac-w243.json',
    dateField: 'cmplnt_fr_dt',
    nullCheck: 'latitude',
    fields: {
      id: 'cmplnt_num',
      type: 'ofns_desc',
      description: 'ofns_desc',
      date: 'cmplnt_fr_dt',
      lat: 'latitude',
      lng: 'longitude',
      address: 'loc_of_occur_desc',
      neighborhood: 'boro_nm',
      district: 'patrol_boro',
      caseNumber: 'cmplnt_num',
    },
  },

  losangeles: {
    id: 'losangeles',
    name: 'Los Angeles',
    state: 'CA',
    center: [34.0522, -118.2437],
    zoom: 11,
    type: 'soda',
    endpoint: 'https://data.lacity.org/resource/2nrs-mtv8.json',
    dateField: 'date_occ',
    nullCheck: 'lat',
    fields: {
      id: 'dr_no',
      type: 'crm_cd_desc',
      description: 'crm_cd_desc',
      date: 'date_occ',
      lat: 'lat',
      lng: 'lon',
      address: 'location',
      neighborhood: 'area_name',
      district: 'area_name',
      caseNumber: 'dr_no',
    },
  },

  sanfrancisco: {
    id: 'sanfrancisco',
    name: 'San Francisco',
    state: 'CA',
    center: [37.7749, -122.4194],
    zoom: 13,
    type: 'soda',
    endpoint: 'https://data.sfgov.org/resource/wg3w-h783.json',
    dateField: 'incident_datetime',
    nullCheck: 'latitude',
    fields: {
      id: 'incident_id',
      type: 'incident_category',
      description: 'incident_description',
      date: 'incident_datetime',
      lat: 'latitude',
      lng: 'longitude',
      address: 'intersection',
      neighborhood: 'analysis_neighborhood',
      district: 'police_district',
      caseNumber: 'incident_id',
    },
  },

  dallas: {
    id: 'dallas',
    name: 'Dallas',
    state: 'TX',
    center: [32.7767, -96.797],
    zoom: 11,
    type: 'soda',
    endpoint: 'https://www.dallasopendata.com/resource/qv6i-rri7.json',
    dateField: 'date1',
    nullCheck: 'geocoded_column',
    coordNested: true,
    fields: {
      id: 'incidentnum',
      type: 'offincident',
      description: 'offincident',
      date: 'date1',
      lat: 'geocoded_column',
      lng: 'geocoded_column',
      address: 'incident_address',
      neighborhood: 'division',
      district: 'division',
      caseNumber: 'incidentnum',
    },
  },
}

export const CITY_LIST = Object.values(CITIES)
