export const CITIES = {
  chicago: {
    id: 'chicago',
    name: 'Chicago',
    state: 'IL',
    center: [41.8781, -87.6298],
    zoom: 11,
    type: 'soda',
    endpoint: 'https://data.cityofchicago.org/resource/ijzp-q8t2.json',
    dateField: 'date',
    nullCheck: 'latitude',
    fields: {
      id: 'id',
      type: 'primary_type',
      description: 'description',
      date: 'date',
      lat: 'latitude',
      lng: 'longitude',
      address: 'block',
      neighborhood: 'community_area',
      district: 'district',
      caseNumber: 'case_number',
    },
    neighborhoodTransform: 'chicago_community_area',
    freshnessTier: 'current',
    statusLabel: 'Updated daily',
  },

  detroit: {
    id: 'detroit',
    name: 'Detroit',
    state: 'MI',
    center: [42.3314, -83.0458],
    zoom: 12,
    type: 'arcgis',
    endpoint: 'https://services2.arcgis.com/qvkbeam7Wirps6zC/arcgis/rest/services/RMS_Crime_Incidents/FeatureServer/0/query',
    dateField: 'incident_occurred_at',
    dateType: 'epoch',
    fields: {
      id: 'crime_id',
      type: 'offense_category',
      description: 'offense_description',
      date: 'incident_occurred_at',
      lat: 'latitude',
      lng: 'longitude',
      address: 'nearest_intersection',
      neighborhood: 'neighborhood',
      district: 'police_precinct',
      caseNumber: 'case_id',
    },
    freshnessTier: 'current',
    statusLabel: 'Updated hourly',
  },

  nyc: {
    id: 'nyc',
    name: 'New York',
    state: 'NY',
    center: [40.7128, -74.006],
    zoom: 11,
    type: 'soda',
    endpoint: 'https://data.cityofnewyork.us/resource/5uac-w243.json',
    dateField: 'cmplnt_fr_dt',
    nullCheck: 'latitude',
    fields: {
      id: 'cmplnt_num',
      type: 'ofns_desc',
      description: 'ofns_desc',
      date: 'cmplnt_fr_dt',
      lat: 'latitude',
      lng: 'longitude',
      address: 'loc_of_occur_desc',
      neighborhood: 'boro_nm',
      district: 'patrol_boro',
      caseNumber: 'cmplnt_num',
    },
    neighborhoodBoundary: {
      url: 'https://services5.arcgis.com/GfwWNkhOj9bNBqoJ/ArcGIS/rest/services/NYC_Neighborhood_Tabulation_Areas_2020/FeatureServer/0/query?where=1%3D1&outFields=NTAName&f=geojson',
      property: 'NTAName',
    },
    freshnessTier: 'stale',
    statusLabel: 'Stale source',
  },

  losangeles: {
    id: 'losangeles',
    name: 'Los Angeles',
    state: 'CA',
    center: [34.0522, -118.2437],
    zoom: 11,
    type: 'soda',
    endpoint: 'https://data.lacity.org/resource/k7nn-b2ep.json',
    dateField: 'date_rptd',
    nullCheck: 'hndrdth_lat',
    fields: {
      id: 'uniquenibrno',
      type: 'nibr_description',
      description: 'nibr_description',
      date: 'date_rptd',
      lat: 'hndrdth_lat',
      lng: 'hndrdth_lon',
      address: 'hndrdth_loc_chk',
      neighborhood: 'area_name',
      district: 'area_name',
      caseNumber: 'caseno',
    },
    neighborhoodBoundary: {
      url: 'https://data.lacity.org/resource/2dna-qi2s.geojson?$select=name,the_geom',
      property: 'name',
    },
    freshnessTier: 'current',
    statusLabel: 'Bi-weekly',
  },

  sanfrancisco: {
    id: 'sanfrancisco',
    name: 'San Francisco',
    state: 'CA',
    center: [37.7749, -122.4194],
    zoom: 13,
    type: 'soda',
    endpoint: 'https://data.sfgov.org/resource/wg3w-h783.json',
    dateField: 'incident_datetime',
    nullCheck: 'latitude',
    fields: {
      id: 'incident_id',
      type: 'incident_category',
      description: 'incident_description',
      date: 'incident_datetime',
      lat: 'latitude',
      lng: 'longitude',
      address: 'intersection',
      neighborhood: 'analysis_neighborhood',
      district: 'police_district',
      caseNumber: 'incident_id',
    },
    freshnessTier: 'current',
    statusLabel: 'Updated daily',
  },

  kansascity: {
    id: 'kansascity',
    name: 'Kansas City',
    state: 'MO',
    center: [39.0997, -94.5786],
    zoom: 12,
    type: 'soda',
    endpoint: 'https://data.kcmo.org/resource/isbe-v4d8.json',
    dateField: 'reported_date',
    nullCheck: 'address',
    coordGeoJson: true,
    fields: {
      id: 'report_no',
      type: 'offense',
      description: 'description',
      date: 'reported_date',
      lat: 'location',
      lng: 'location',
      address: 'address',
      neighborhood: 'area',
      district: 'beat',
      caseNumber: 'report_no',
    },
    neighborhoodBoundary: {
      url: 'https://data.kcmo.org/resource/vq6h-tqrf.geojson?$select=nbhname,the_geom',
      property: 'nbhname',
    },
    freshnessTier: 'stale',
    statusLabel: 'Stale source',
  },

  seattle: {
    id: 'seattle',
    name: 'Seattle',
    state: 'WA',
    center: [47.6062, -122.3321],
    zoom: 12,
    type: 'soda',
    endpoint: 'https://data.seattle.gov/resource/tazs-3rd5.json',
    dateField: 'report_date_time',
    nullCheck: 'latitude',
    fields: {
      id: 'report_number',
      type: 'offense_sub_category',
      description: 'nibrs_offense_code_description',
      date: 'report_date_time',
      lat: 'latitude',
      lng: 'longitude',
      address: 'block_address',
      neighborhood: 'neighborhood',
      district: 'sector',
      caseNumber: 'report_number',
    },
    freshnessTier: 'current',
    statusLabel: 'Updated daily',
  },

  dallas: {
    id: 'dallas',
    name: 'Dallas',
    state: 'TX',
    center: [32.7767, -96.797],
    zoom: 11,
    type: 'soda',
    endpoint: 'https://www.dallasopendata.com/resource/qv6i-rri7.json',
    dateField: 'date1',
    nullCheck: 'geocoded_column',
    coordNested: true,
    fields: {
      id: 'incidentnum',
      type: 'offincident',
      description: 'offincident',
      date: 'date1',
      lat: 'geocoded_column',
      lng: 'geocoded_column',
      address: 'incident_address',
      neighborhood: 'division',
      district: 'division',
      caseNumber: 'incidentnum',
    },
    neighborhoodBoundary: {
      url: 'https://www.dallasopendata.com/resource/2ted-gecp.geojson?$select=common_nam,the_geom',
      property: 'common_nam',
    },
    neighborhoodTransform: 'dallas_division',
    freshnessTier: 'current',
    statusLabel: 'Updated daily',
  },

  oakland: {
    id: 'oakland',
    name: 'Oakland',
    state: 'CA',
    center: [37.8044, -122.2712],
    zoom: 12,
    type: 'soda',
    endpoint: 'https://data.oaklandca.gov/resource/ppgh-7dqv.json',
    dateField: 'datetime',
    nullCheck: 'location',
    coordGeoJson: true,
    fields: {
      id: 'casenumber',
      type: 'crimetype',
      description: 'description',
      date: 'datetime',
      lat: 'location',
      lng: 'location',
      address: 'address',
      neighborhood: 'policebeat',
      district: 'policebeat',
      caseNumber: 'casenumber',
    },
    neighborhoodBoundary: {
      url: 'https://data.oaklandca.gov/resource/sb4q-6bkc.geojson?$select=neighbhd,the_geom',
      property: 'neighbhd',
    },
    freshnessTier: 'current',
    statusLabel: 'Updated daily',
  },

  batonrouge: {
    id: 'batonrouge',
    name: 'Baton Rouge',
    state: 'LA',
    center: [30.4515, -91.1871],
    zoom: 12,
    type: 'soda',
    endpoint: 'https://data.brla.gov/resource/pbin-pcm7.json',
    dateField: 'report_date',
    nullCheck: 'latitude',
    fields: {
      id: 'incident_number',
      type: 'offense_description',
      description: 'statute_description',
      date: 'report_date',
      lat: 'latitude',
      lng: 'longitude',
      address: 'street',
      neighborhood: 'neighborhood',
      district: 'district',
      caseNumber: 'incident_number',
    },
    freshnessTier: 'current',
    statusLabel: 'Updated daily',
  },

  atlanta: {
    id: 'atlanta',
    name: 'Atlanta',
    state: 'GA',
    center: [33.749, -84.388],
    zoom: 12,
    type: 'arcgis',
    endpoint: 'https://services3.arcgis.com/Et5Qfajgiyosiw4d/arcgis/rest/services/OpenDataWebsite_Crime_view/FeatureServer/0/query',
    dateField: 'OccurredFromDate',
    dateType: 'epoch',
    where: 'Latitude IS NOT NULL AND Longitude IS NOT NULL',
    outFields: 'IncidentNumber,ReportNumber,OccurredFromDate,NIBRS_Offense,StreetAddress,Latitude,Longitude,Zone,BEAT,NPU,NhoodName',
    maxFutureDays: 7,
    fields: {
      id: 'IncidentNumber',
      type: 'NIBRS_Offense',
      description: 'NIBRS_Offense',
      date: 'OccurredFromDate',
      lat: 'Latitude',
      lng: 'Longitude',
      address: 'StreetAddress',
      neighborhood: 'NhoodName',
      district: 'Zone',
      caseNumber: 'ReportNumber',
    },
    freshnessTier: 'current',
    statusLabel: 'Updated daily',
  },

  washingtondc: {
    id: 'washingtondc',
    name: 'Washington',
    state: 'DC',
    center: [38.9072, -77.0369],
    zoom: 12,
    type: 'arcgis',
    endpoint: 'https://maps2.dcgis.dc.gov/dcgis/rest/services/FEEDS/MPD/FeatureServer/41/query',
    dateField: 'REPORT_DAT',
    dateType: 'epoch',
    where: 'LATITUDE IS NOT NULL AND LONGITUDE IS NOT NULL AND LATITUDE <> 0 AND LONGITUDE <> 0',
    outFields: 'CCN,REPORT_DAT,BLOCK,OFFENSE,METHOD,DISTRICT,PSA,NEIGHBORHOOD_CLUSTER,LATITUDE,LONGITUDE',
    fields: {
      id: 'CCN',
      type: 'OFFENSE',
      description: 'METHOD',
      date: 'REPORT_DAT',
      lat: 'LATITUDE',
      lng: 'LONGITUDE',
      address: 'BLOCK',
      neighborhood: 'NEIGHBORHOOD_CLUSTER',
      district: 'DISTRICT',
      caseNumber: 'CCN',
    },
    neighborhoodBoundary: {
      url: 'https://maps2.dcgis.dc.gov/dcgis/rest/services/DCGIS_DATA/Administrative_Other_Boundaries_WebMercator/MapServer/17/query?where=1%3D1&outFields=NAME&f=geojson',
      property: 'NAME',
    },
    freshnessTier: 'current',
    statusLabel: 'Updated daily',
  },
}

export const CITY_LIST = Object.values(CITIES)

export const CITY_GROUPS = [
  { id: 'current', label: 'Current Feeds' },
  { id: 'stale', label: 'Stale Feeds' },
]
